description: Running on A100s Amulet configs for my PEFT.

target:
  service: sing
  #* a100
  workspace_name: csr-sing-icode-ws01-westus3
  name: csr-sing-icode-wu3
  # v100
  # workspace_name: csr-sing-ws01-westus2
  # name: csr-sing-wu2

environment:
  image: amlt-sing/deepspeed-0.4-pytorch-1.10.0-cuda11.4-a100     
  setup:
    - set -x
    - cd /azure/yingxiu/Yingxiu_Intern/PET/
    - pip install -r requirements.txt 
    - nvcc --version
    # - pip install deepspeed
    - pip install datasets
    - pip install nltk
    - python3 -c "import nltk; nltk.download('punkt')"

storage:
  # v100_storage: 
  #   storage_account_name: sdrgmainz01wus2
  #   container_name: user
  #   mount_dir: /azure
  # model_storage:
  #   storage_account_name: sdrgprmblob01scus
  #   container_name: data
  #   mount_dir: /mnt
  #   mount_options: ['--file-cache-timeout-in-seconds=60']
  data_storage:
    storage_account_name: sdrgstorage01wus2
    container_name: amulet
    mount_dir: /azure

  
code:
  local_dir: $CONFIG_DIR/

jobs:
# - name: adapter_4gpu_run1a
- name: a100_adapter_8gpu_run0
  sku: G8
  command:
  - ls -l /azure/yingxiu/
  # - ls -l /mnt/users/yingxiu/
  # - cd /mnt/users/yingxiu/Yingxiu_Intern/PET/
  - cd /azure/yingxiu/Yingxiu_Intern/PET/
  - bash scripts/ds_run.sh
  - echo FINISH! Congrats!!!
